export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_CLEAR_ERRORS = "LOGIN_CLEAR_ERRORS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_CLEAR_ERRORS = "REGISTER_CLEAR_ERRORS";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";
export const LOAD_CLEAR_ERRORS = "LOAD_CLEAR_ERRORS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_CLEAR_ERRORS = "LOGOUT_CLEAR_ERRORS";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const UPDATE_RESET = "UPDATE_RESET"
export const UPDATE_CLEAR_ERRORS = "UPDATE_CLEAR_ERRORS";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
export const UPDATE_PASSWORD_CLEAR_ERRORS = "UPDATE_PASSWORD_CLEAR_ERRORS";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_CLEAR_ERRORS = "FORGOT_PASSWORD_CLEAR_ERRORS";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CLEAR_ERRORS = "RESET_PASSWORD_CLEAR_ERRORS";

export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";
export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL";
export const ADMIN_ALL_USERS_CLEAR_ERRORS = "ADMIN_ALL_USERS_CLEAR_ERRORS";


export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_CLEAR_ERRORS = "USER_DETAILS_CLEAR_ERRORS";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
export const DELETE_USER_CLEAR_ERRORS = "DELETE_USER_CLEAR_ERRORS";


export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_CLEAR_ERRORS = "UPDATE_USER_CLEAR_ERRORS";